# permissions for end users to view gpujobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpujob-viewer-role
rules:
- apiGroups:
  - sigma.ihomefnt.com
  resources:
  - gpujobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sigma.ihomefnt.com
  resources:
  - gpujobs/status
  verbs:
  - get
